##<b> The International Cricket Council (ICC) is the world governing body of cricket. It was founded as the Imperial Cricket Conference in 1909 by representatives from Australia, England and South Africa. It was renamed as the International Cricket Conference in 1965, and took up its current name in 1989. It organises world championship events such as Cricket World Cup, Women's Cricket World Cup, ICC T20 World Cup, ICC Women's T20 World Cup, ICC Champions Trophy and Under-19 Cricket World Cup.</b>

<br>

## <b> You recently got a lucky break in the field of Data Science. You got a job of Data Scientist at ICC. You are part of the Analytics Team which is involved in pre-match analyses, live-match analyses and post-match analyses. </b>

<br>

## <b>This data consists of 1417 T20 matches. Each row corresponds to a single T20 match. As a data scientist, you have to first explore the data and check its sanity. </b>

<br>

## <u><b>Further you are required to do some analyses :</b></u>
* ### Rename all the column names to their appropriate names, for example meta.created should be renamed as created_date
* ### Find out the top three venues which hosted the greatest number of matches.
* ### Find out the pair of cricket teams who played the most number of T20 matches against each other.
* ### Print the top five teams by their win percentages. Win percentage is defined as the number of matches won divided by the number of matches played and then multiplied by 100.
* ### Write a function to get the scorecard of each match. This function would take the innings value as argument and return two scorecard dataframes each for one team as shown below. So the first dataframe would contain the top 4 scorers of the team who batted first and the top 4 bowlers of the opponent team. And the second dataframe would contain the top 4 scorers of the team who batted second and the top 4 bowlers of the opponent team.

In [40]:
import numpy as np 
import pandas as pd 
import seaborn as sns 
import matplotlib.pyplot as plt

In [41]:
df = pd.read_csv('International_T20_Data.csv')
pd.set_option('display.max_columns' , None)
df.sample(5)

,innings,meta.data_version,meta.created,meta.revision,info.dates,info.gender,info.match_type,info.outcome.by.wickets,info.outcome.winner,info.overs,info.player_of_match,info.teams,info.toss.decision,info.toss.winner,info.umpires,info.venue,info.city,info.outcome.by.runs,info.match_type_number,info.neutral_venue,info.outcome.method,info.outcome.result,info.outcome.eliminator,info.supersubs.New Zealand,info.supersubs.South Africa,info.bowl_out,info.outcome.bowl_out
78,"[{'1st innings': {'team': 'Pakistan', 'deliver...",0.9,2020-07-06,1,['2018-01-28'],male,T20,NaN,Pakistan,20,['Shadab Khan'],"['Pakistan', 'New Zealand']",bat,Pakistan,"['SB Haig', 'WR Knights']",Bay Oval,Mount Maunganui,18.0,641.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1365,"[{'1st innings': {'team': 'Sri Lanka', 'delive...",0.9,2016-03-21,2,"[datetime.date(2016, 3, 20)]",female,T20,NaN,Sri Lanka,20,['CJ Metcalfe'],"['Sri Lanka', 'Ireland']",bat,Sri Lanka,"['VA Kulkarni', 'CA Polosak']","Punjab Cricket Association IS Bindra Stadium, ...",Mohali,14.0,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
870,"[{'1st innings': {'team': 'New Zealand', 'deli...",0.9,2010-05-18,2,"[datetime.date(2010, 5, 8)]",male,T20,NaN,New Zealand,20,['IG Butler'],"['New Zealand', 'Pakistan']",field,Pakistan,"['BR Doctrove', 'IJ Gould']","Kensington Oval, Bridgetown",Barbados,1.0,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1110,"[{'1st innings': {'team': 'Ireland', 'deliveri...",0.9,2013-12-03,1,"[datetime.date(2013, 11, 16)]",male,T20,NaN,Ireland,20,['A Bagai'],"['Canada', 'Ireland']",field,Canada,"['MA Gough', 'REJ Martinesz']",Sheikh Zayed Stadium,Abu Dhabi,2.0,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1312,"[{'1st innings': {'team': 'Oman', 'deliveries'...",0.9,2015-11-29,3,"[datetime.date(2015, 11, 25)]",male,T20,NaN,Oman,20,NaN,"['Hong Kong', 'Oman']",field,Hong Kong,"['VA Kulkarni', 'Sarika Prasad']",Sheikh Zayed Stadium,Abu Dhabi,4.0,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [42]:
df.shape

(1417, 27)

In [43]:
print(df.columns)

Index(['innings', 'meta.data_version', 'meta.created', 'meta.revision',
       'info.dates', 'info.gender', 'info.match_type',
       'info.outcome.by.wickets', 'info.outcome.winner', 'info.overs',
       'info.player_of_match', 'info.teams', 'info.toss.decision',
       'info.toss.winner', 'info.umpires', 'info.venue', 'info.city',
       'info.outcome.by.runs', 'info.match_type_number', 'info.neutral_venue',
       'info.outcome.method', 'info.outcome.result', 'info.outcome.eliminator',
       'info.supersubs.New Zealand', 'info.supersubs.South Africa',
       'info.bowl_out', 'info.outcome.bowl_out'],
      dtype='object')

1) Rename all the column names to their appropriate names, for example meta.created should be renamed as created_date

In [44]:
df.rename(columns = {'meta.data_version' : 'data_version' , 'meta.created' : 'created' , 'meta.revision' : 'revision' , 
                     'info.dates' : 'dates' , 'info.gender' : 'gender' , 'info.match_type' : 'match_type' ,
                     'info.outcome.by.wickets' : 'outcome.by.wickets' , 'info.outcome.winner' : 'outcome.winner' , 'info.overs' : 'overs' ,
                      'info.player_of_match' : 'player_of_match' , 'info.teams' : 'teams' , 'info.toss.decision' : 'toss.decision' ,
                       'info.toss.winner' : 'toss.winner', 'info.umpires' : 'umpires', 'info.venue' : 'venue', 'info.city' : 'city',
                       'info.outcome.by.runs' : 'outcome.by.runs', 'info.match_type_number' : 'match_type_number', 'info.neutral_venue' : 'neutral_venue',
                       'info.outcome.method' : 'outcome.method', 'info.outcome.result' : 'outcome.result', 'info.outcome.eliminator' : 'outcome.eliminator',
                       'info.supersubs.New Zealand' : 'supersubs.New Zealand', 'info.supersubs.South Africa' : 'supersubs.South Africa',
                       'info.bowl_out' : 'bowl_out', 'info.outcome.bowl_out' : 'outcome.bowl_out'
                    } , inplace = True)

In [45]:
df.sample(5)

,innings,data_version,created,revision,dates,gender,match_type,outcome.by.wickets,outcome.winner,overs,player_of_match,teams,toss.decision,toss.winner,umpires,venue,city,outcome.by.runs,match_type_number,neutral_venue,outcome.method,outcome.result,outcome.eliminator,supersubs.New Zealand,supersubs.South Africa,bowl_out,outcome.bowl_out
815,"[{'1st innings': {'team': 'Pakistan', 'deliver...",0.9,2009-08-15,2,"[datetime.date(2009, 6, 9)]",male,T20,NaN,Pakistan,20,['Kamran Akmal'],"['Netherlands', 'Pakistan']",bat,Pakistan,"['BR Doctrove', 'AM Saheba']",Lord's,London,82.0,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1116,"[{'1st innings': {'team': 'Kenya', 'deliveries...",0.9,2013-12-17,1,"[datetime.date(2013, 11, 26)]",male,T20,NaN,Kenya,20,['SO Tikolo'],"['Canada', 'Kenya']",bat,Kenya,"['Sarika Prasad', 'DJ Walker']",Sharjah Cricket Stadium,NaN,21.0,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
754,"[{'1st innings': {'team': 'West Indies', 'deli...",0.9,2013-02-18,1,"[datetime.date(2007, 6, 28)]",male,T20,NaN,West Indies,20,['PD Collingwood'],"['England', 'West Indies']",bat,West Indies,"['PJ Hartley', 'NJ Llong']",Kennington Oval,London,15.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
235,"[{'1st innings': {'team': 'West Indies', 'deli...",0.9,2020-07-01,1,['2018-11-14'],female,T20,NaN,West Indies,20,['SR Taylor'],"['West Indies', 'South Africa']",field,South Africa,"['Sharfuddoula', 'Ahsan Raza']","Daren Sammy National Cricket Stadium, Gros Islet",St Lucia,31.0,525.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
339,"[{'1st innings': {'team': 'Nepal', 'deliveries...",0.9,2020-01-06,1,['2019-02-27'],female,T20,NaN,Nepal,20,['RC Belbashi'],"['Kuwait', 'Nepal']",field,Kuwait,"['Akbar Ali', 'Tabarak Dar']",Asian Institute of Technology Ground,Bangkok,30.0,597.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

2) Find out the top three venues which hosted the greatest number of matches.

In [46]:
Top_3_Venues = df['venue'].value_counts().head(3).index
Top_3_Venues

Index(['Dubai International Cricket Stadium', 'Sheikh Zayed Stadium',
       'Shere Bangla National Stadium'],
      dtype='object', name='venue')

In [47]:
df['match_type'].value_counts()

match_type
T20    1417
Name: count, dtype: int64

3) Find out the pair of cricket teams who played the most number of T20 matches against each other.

In [48]:
df['teams'].value_counts().head(1).index

Index(['['England', 'Pakistan']'], dtype='object', name='teams')

4) Print the top five teams by their win percentages. Win percentage is defined as the number of matches won divided by the number of matches played and then multiplied by 100.

In [49]:
s1 = list(df['outcome.winner'].value_counts().index)

In [50]:
s1

['Australia',
 'England',
 'India',
 'Pakistan',
 'South Africa',
 'New Zealand',
 'West Indies',
 'Sri Lanka',
 'Afghanistan',
 'Bangladesh',
 'Ireland',
 'Netherlands',
 'Scotland',
 'United Arab Emirates',
 'Namibia',
 'Zimbabwe',
 'Nepal',
 'Papua New Guinea',
 'Thailand',
 'Hong Kong',
 'Malaysia',
 'Oman',
 'Germany',
 'Kenya',
 'Singapore',
 'Canada',
 'Jersey',
 'Uganda',
 'United States of America',
 'China',
 'Spain',
 'Vanuatu',
 'Bermuda',
 'Belgium',
 'Kuwait',
 'Guernsey',
 'Japan',
 'Rwanda',
 'Sierra Leone',
 'Nigeria',
 'Romania',
 'Maldives',
 'Botswana',
 'Qatar',
 'Tanzania',
 'Italy',
 'Denmark',
 'Indonesia',
 'Mozambique',
 'ICC World XI',
 'Malawi',
 'Philippines',
 'Samoa',
 'Portugal',
 'Bahrain',
 'Bulgaria']

In [51]:
l = []
for i in s1:
    l.append((df['teams'].str.contains(i).sum()).tolist())
l

[214,
 216,
 204,
 226,
 192,
 190,
 195,
 182,
 75,
 137,
 128,
 80,
 67,
 56,
 34,
 76,
 40,
 35,
 35,
 50,
 35,
 35,
 17,
 30,
 18,
 23,
 10,
 13,
 14,
 9,
 6,
 12,
 12,
 3,
 12,
 6,
 6,
 6,
 7,
 11,
 3,
 10,
 16,
 6,
 3,
 4,
 6,
 3,
 6,
 4,
 3,
 4,
 2,
 3,
 2,
 3]

In [52]:
l1 = (df['outcome.winner'].value_counts().values.tolist())
l1

[132,
 130,
 121,
 117,
 101,
 97,
 85,
 69,
 51,
 50,
 48,
 38,
 33,
 25,
 25,
 22,
 22,
 21,
 17,
 17,
 15,
 14,
 13,
 11,
 9,
 8,
 6,
 6,
 5,
 5,
 5,
 5,
 4,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1]

In [53]:
ans = []
for i in range(len(l1)):
    ans.append(np.round((l1[i]/l[i]) * 100 , 2).tolist())
len(ans)

56

In [54]:
win = pd.DataFrame({'Country' : s1 , 'Win Percentage' : ans})
win
win_Percenatge = (win.sort_values(by = 'Win Percentage' , ascending = False).head().iloc[: , 0].values)
win_Percenatge
win.sort_values(by = 'Win Percentage' , ascending = False).head()

        Country  Win Percentage
33      Belgium          100.00
30        Spain           83.33
22      Germany           76.47
14      Namibia           73.53
8   Afghanistan           68.00

5) Write a function to get the scorecard of each match. This function would take the innings value as argument and return two scorecard dataframes each for one team as shown below. So the first dataframe would contain the top 4 scorers of the team who batted first and the top 4 bowlers of the opponent team. And the second dataframe would contain the top 4 scorers of the team who batted second and the top 4 bowlers of the opponent team.

In [55]:
def get_scorecard(data):

    # First innings
    bat1 = data[data['innings']==1].groupby('batter')['runs_off_bat'].sum().sort_values(ascending=False).head(4)
    bowl1 = data[data['innings']==1].groupby('bowler')['is_wicket'].sum().sort_values(ascending=False).head(4)

    scorecard1 = pd.concat([bat1, bowl1], axis=1)

    # Second innings
    bat2 = data[data['innings']==2].groupby('batter')['runs_off_bat'].sum().sort_values(ascending=False).head(4)
    bowl2 = data[data['innings']==2].groupby('bowler')['is_wicket'].sum().sort_values(ascending=False).head(4)

    scorecard2 = pd.concat([bat2, bowl2], axis=1)

    return scorecard1, scorecard2

In [56]:
import ast
for i in range(len(df)):

    match_innings_raw = df['innings'].iloc[i]

    match_innings_parsed = ast.literal_eval(match_innings_raw)

    rows = []
    for inning_index, inning_detail in enumerate(match_innings_parsed): # Use the parsed data
        for inning_name, inning_content in inning_detail.items():
            team = inning_content['team']
            deliveries = inning_content['deliveries']
            for delivery in deliveries:
                for over_ball, ball_data in delivery.items():
                    batsman = ball_data.get('batsman')
                    bowler = ball_data.get('bowler')
                    # Extract runs scored by batsman from the 'runs' dictionary, default to 0 if not found
                    runs_off_bat = ball_data.get('runs', {}).get('batsman', 0)
                    # Check if a wicket occurred in this delivery, assign 1 if yes, 0 if no
                    is_wicket = 1 if 'wicket' in ball_data else 0
                    rows.append({
                        'innings': inning_index + 1, # 'innings' column represents the inning number (1st, 2nd)
                        'team': team,
                        'batter': batsman,
                        'bowler': bowler,
                        'runs_off_bat': runs_off_bat,
                        'is_wicket': is_wicket
                    })

    match_data_for_scorecard = pd.DataFrame(rows)

    score1, score2 = get_scorecard(match_data_for_scorecard)

    print(f"\n\nMatch : {i+1}\n")
    print("Team 1 Score:\n")
    print(score1)
    print("\nTeam 2 Score:\n")
    print(score2)

Match : 1

Team 1 Score:

                 runs_off_bat  is_wicket
AJ Finch                 43.0        NaN
M Klinger                38.0        NaN
TM Head                  31.0        NaN
AJ Turner                18.0        NaN
SL Malinga                NaN        2.0
DAS Gunaratne             NaN        1.0
JRMVB Sanjaya             NaN        1.0
KMDN Kulasekara           NaN        1.0

Team 2 Score:

                 runs_off_bat  is_wicket
DAS Gunaratne            52.0        NaN
EMDY Munaweera           44.0        NaN
N Dickwella              30.0        NaN
TAM Siriwardana          15.0        NaN
A Zampa                   NaN        2.0
AJ Turner                 NaN        2.0
PJ Cummins                NaN        1.0
AJ Tye                    NaN        0.0


Match : 2

Team 1 Score:

                 runs_off_bat  is_wicket
MC Henriques             56.0        NaN
M Klinger                43.0        NaN
BR Dunk                  32.0        NaN
AJ Finch                 12.0        NaN
KMDN Kulasekara           NaN        4.0
JRMVB Sanjaya             NaN        2.0
SL Malinga                NaN        2.0
DAS Gunaratne             NaN        1.0

Team 2 Score:

                 runs_off_bat  is_wicket
DAS Gunaratne            84.0        NaN
CK Kapugedera            32.0        NaN
N Dickwella              14.0        NaN
KMDN Kulasekara          12.0        NaN
AJ Tye                    NaN        3.0
JP Faulkner               NaN        2.0
AJ Turner                 NaN        1.0
JA Richardson             NaN        1.0


Match : 3

Team 1 Score:

                 runs_off_bat  is_wicket
M Klinger                62.0        NaN
AJ Finch                 53.0        NaN
TM Head                  30.0        NaN
BR Dunk                  28.0        NaN
SL Malinga                NaN        3.0
MD Shanaka                NaN        2.0
S Prasanna                NaN        1.0
KMDN Kulasekara           NaN        0.0

Team 2 Score:

                 runs_off_bat  is_wicket
EMDY Munaweera           37.0        NaN
TAM Siriwardana          35.0        NaN
BKG Mendis               14.0        NaN
WU Tharanga              14.0        NaN
A Zampa                   NaN        3.0
JP Faulkner               NaN        3.0
PJ Cummins                NaN        2.0
TM Head                   NaN        1.0


Match : 4

Team 1 Score:

              runs_off_bat  is_wicket
Nizakat Khan          62.0        NaN
Babar Hayat           49.0        NaN
Ehsan Khan            29.0        NaN
Tanwir Afzal           6.0        NaN
CA Young               NaN        2.0
AR McBrine             NaN        1.0
J Mulder               NaN        1.0
KJ O'Brien             NaN        1.0

Team 2 Score:

               runs_off_bat  is_wicket
GJ Thompson            44.0        NaN
KJ O'Brien             32.0        NaN
DA Rankin              15.0        NaN
AR McBrine             10.0        NaN
Aizaz Khan              NaN        3.0
Nadeem Ahmed            NaN        2.0
Tanwir Afzal            NaN        2.0
Tanveer Ahmed           NaN        2.0


Match : 5

Team 1 Score:

               runs_off_bat  is_wicket
E Chigumbura           54.0        NaN
MN Waller              30.0        NaN
H Masakadza            25.0        NaN
Sikandar Raza          20.0        NaN
AR Patel                NaN        2.0
JJ Bumrah               NaN        2.0
JD Unadkat              NaN        1.0
R Dhawan                NaN        1.0

Team 2 Score:

               runs_off_bat  is_wicket
MK Pandey              48.0        NaN
Mandeep Singh          31.0        NaN
AT Rayudu              19.0        NaN
KM Jadhav              19.0        NaN
CJ Chibhabha            NaN        2.0
T Muzarabani            NaN        2.0
N Madziva               NaN        1.0
DT Tiripano             NaN        1.0


Match : 6

Team 1 Score:

              runs_off_bat  is_wicket
PJ Moor               31.0        NaN
MN Waller             14.0        NaN
DT Tiripano           11.0        NaN
CJ Chibhabha          10.0        NaN
BB Sran                NaN        4.0
JJ Bumrah              NaN        3.0
DS Kulkarni            NaN        1.0
YS Chahal              NaN        1.0

Team 2 Score:

               runs_off_bat  is_wicket
Mandeep Singh          52.0        NaN
KL Rahul               47.0        NaN
AG Cremer               NaN        0.0
CJ Chibhabha            NaN        0.0
DT Tiripano             NaN        0.0
N Madziva               NaN        0.0


Match : 7

Team 1 Score:

              runs_off_bat  is_wicket
KM Jadhav             58.0        NaN
KL Rahul              22.0        NaN
AT Rayudu             20.0        NaN
AR Patel              20.0        NaN
DT Tiripano            NaN        3.0
N Madziva              NaN        2.0
AG Cremer              NaN        1.0
CJ Chibhabha           NaN        0.0

Team 2 Score:

              runs_off_bat  is_wicket
V Sibanda             28.0        NaN
PJ Moor               26.0        NaN
T Maruma              23.0        NaN
E Chigumbura          16.0        NaN
BB Sran                NaN        2.0
DS Kulkarni            NaN        2.0
AR Patel               NaN        1.0
YS Chahal              NaN        1.0


Match : 8

Team 1 Score:

                  runs_off_bat  is_wicket
Mahmudullah               52.0        NaN
Mosaddek Hossain          20.0        NaN
Sabbir Rahman             16.0        NaN
Shakib Al Hasan           14.0        NaN
LH Ferguson                NaN        3.0
BM Wheeler                 NaN        2.0
C de Grandhomme            NaN        1.0
MJ Henry                   NaN        1.0

Team 2 Score:

                   runs_off_bat  is_wicket
KS Williamson              73.0        NaN
C de Grandhomme            41.0        NaN
CJ Anderson                13.0        NaN
TC Bruce                    7.0        NaN
Mashrafe Mortaza            NaN        1.0
Mustafizur Rahman           NaN        1.0
Shakib Al Hasan             NaN        1.0
Rubel Hossain               NaN        1.0


Match : 9

Team 1 Score:

                  runs_off_bat  is_wicket
C Munro                  101.0        NaN
TC Bruce                  59.0        NaN
KS Williamson             12.0        NaN
JDS Neesham                5.0        NaN
Rubel Hossain              NaN        4.0
Mashrafe Mortaza           NaN        1.0
Shakib Al Hasan            NaN        1.0
Mosaddek Hossain           NaN        1.0

Team 2 Score:

                 runs_off_bat  is_wicket
Sabbir Rahman            48.0        NaN
Soumya Sarkar            39.0        NaN
Mahmudullah              19.0        NaN
Tamim Iqbal              13.0        NaN
IS Sodhi                  NaN        3.0
BM Wheeler                NaN        2.0
KS Williamson             NaN        2.0
C de Grandhomme           NaN        1.0


Match : 10

Team 1 Score:

                  runs_off_bat  is_wicket
CJ Anderson               94.0        NaN
KS Williamson             60.0        NaN
JDS Neesham               15.0        NaN
TC Bruce                   5.0        NaN
Rubel Hossain              NaN        3.0
Mosaddek Hossain           NaN        1.0
Mashrafe Mortaza           NaN        0.0
Shakib Al Hasan            NaN        0.0

Team 2 Score:

                 runs_off_bat  is_wicket
Soumya Sarkar            42.0        NaN
Shakib Al Hasan          41.0        NaN
Tamim Iqbal              24.0        NaN
Mahmudullah              18.0        NaN
IS Sodhi                  NaN        2.0
TA Boult                  NaN        2.0
KS Williamson             NaN        1.0
MJ Santner                NaN        1.0


Match : 11

Team 1 Score:

                 runs_off_bat  is_wicket
HM Amla                  62.0        NaN
F du Plessis             36.0        NaN
JP Duminy                29.0        NaN
AB de Villiers           26.0        NaN
TA Boult                  NaN        2.0
C de Grandhomme           NaN        2.0
TG Southee                NaN        1.0
BM Wheeler                NaN        1.0

Team 2 Score:

                 runs_off_bat  is_wicket
TC Bruce                 33.0        NaN
TG Southee               20.0        NaN
C de Grandhomme          15.0        NaN
KS Williamson            13.0        NaN
Imran Tahir               NaN        5.0
AL Phehlukwayo            NaN        3.0
CH Morris                 NaN        2.0
D Paterson                NaN        0.0


Match : 12

Team 1 Score:

                runs_off_bat  is_wicket
AB de Villiers          65.0        NaN
F Behardien             64.0        NaN
DA Miller                9.0        NaN
RR Hendricks             3.0        NaN
MA Wood                  NaN        2.0
DJ Willey                NaN        1.0
CJ Jordan                NaN        0.0
LA Dawson                NaN        0.0

Team 2 Score:

                runs_off_bat  is_wicket
JM Bairstow             60.0        NaN
AD Hales                47.0        NaN
JJ Roy                  28.0        NaN
AL Phehlukwayo           NaN        1.0
D Pretorius              NaN        0.0
Imran Tahir              NaN        0.0
JT Smuts                 NaN        0.0


Match : 13

Team 1 Score:

                runs_off_bat  is_wicket
AB de Villiers          46.0        NaN
JT Smuts                45.0        NaN
F Behardien             32.0        NaN
M Mosehle               15.0        NaN
TK Curran                NaN        3.0
LE Plunkett              NaN        2.0
CJ Jordan                NaN        1.0
LA Dawson                NaN        1.0

Team 2 Score:

                runs_off_bat  is_wicket
JJ Roy                  67.0        NaN
JM Bairstow             47.0        NaN
LS Livingstone          16.0        NaN
JC Buttler              10.0        NaN
CH Morris                NaN        3.0
AL Phehlukwayo           NaN        2.0
D Paterson               NaN        1.0
JT Smuts                 NaN        0.0


Match : 14

Team 1 Score:

                runs_off_bat  is_wicket
DJ Malan                78.0        NaN
AD Hales                36.0        NaN
JC Buttler              31.0        NaN
SW Billings             12.0        NaN
D Paterson               NaN        4.0
AL Phehlukwayo           NaN        2.0
Imran Tahir              NaN        1.0
M Morkel                 NaN        1.0

Team 2 Score:

                runs_off_bat  is_wicket
M Mosehle               36.0        NaN
AB de Villiers          35.0        NaN
JT Smuts                29.0        NaN
AL Phehlukwayo          27.0        NaN
CJ Jordan                NaN        3.0
TK Curran                NaN        2.0
LE Plunkett              NaN        1.0
MS Crane                 NaN        1.0


Match : 15

Team 1 Score:

             runs_off_bat  is_wicket
E Lewis              51.0        NaN
CH Gayle             40.0        NaN
R Powell             28.0        NaN
CAK Walton           13.0        NaN
LE Plunkett           NaN        4.0
AU Rashid             NaN        3.0
CJ Jordan             NaN        1.0
TK Curran             NaN        1.0

Team 2 Score:

               runs_off_bat  is_wicket
AD Hales               43.0        NaN
JC Buttler             30.0        NaN
JM Bairstow            27.0        NaN
LE Plunkett            18.0        NaN
CR Brathwaite           NaN        3.0
KOK Williams            NaN        3.0
SP Narine               NaN        2.0
AR Nurse                NaN        1.0


Match : 16

Team 1 Score:

              runs_off_bat  is_wicket
MS Dhoni              36.0        NaN
SK Raina              34.0        NaN
V Kohli               29.0        NaN
Yuvraj Singh          12.0        NaN
CJ Jordan              NaN        2.0
MM Ali                 NaN        2.0
BA Stokes              NaN        1.0
LE Plunkett            NaN        1.0

Team 2 Score:

               runs_off_bat  is_wicket
EJG Morgan             51.0        NaN
JE Root                46.0        NaN
SW Billings            22.0        NaN
JJ Roy                 19.0        NaN
YS Chahal               NaN        2.0
Parvez Rasool           NaN        1.0
HH Pandya               NaN        0.0
A Nehra                 NaN        0.0


Match : 17

Team 1 Score:

           runs_off_bat  is_wicket
KL Rahul           71.0        NaN
MK Pandey          30.0        NaN
V Kohli            21.0        NaN
SK Raina            7.0        NaN
CJ Jordan           NaN        5.0
AU Rashid           NaN        1.0
TS Mills            NaN        1.0
MM Ali              NaN        1.0

Team 2 Score:

            runs_off_bat  is_wicket
BA Stokes           38.0        NaN
JE Root             38.0        NaN
EJG Morgan          17.0        NaN
JC Buttler          15.0        NaN
A Nehra              NaN        3.0
JJ Bumrah            NaN        2.0
A Mishra             NaN        1.0
SK Raina             NaN        0.0


Match : 18

Team 1 Score:

              runs_off_bat  is_wicket
SK Raina              63.0        NaN
MS Dhoni              56.0        NaN
Yuvraj Singh          27.0        NaN
KL Rahul              22.0        NaN
CJ Jordan              NaN        3.0
BA Stokes              NaN        1.0
TS Mills               NaN        1.0
LE Plunkett            NaN        1.0

Team 2 Score:

            runs_off_bat  is_wicket
JE Root             42.0        NaN
EJG Morgan          40.0        NaN
JJ Roy              32.0        NaN
BA Stokes            6.0        NaN
YS Chahal            NaN        6.0
JJ Bumrah            NaN        3.0
A Mishra             NaN        1.0
A Nehra              NaN        0.0


Match : 19

Team 1 Score:

                 runs_off_bat  is_wicket
SR Thompson              56.0        NaN
GC Wilson                41.0        NaN
WTS Porterfield          39.0        NaN
L Tucker                 14.0        NaN
Amir Hamza                NaN        2.0
Rashid Khan               NaN        2.0
Mohammad Nabi             NaN        1.0
Karim Janat               NaN        0.0

Team 2 Score:

                    runs_off_bat  is_wicket
Samiullah Shenwari          56.0        NaN
Mohammad Shahzad            47.0        NaN
Najeeb Tarakai              27.0        NaN
Asghar Stanikzai            20.0        NaN
SR Thompson                  NaN        2.0
CA Young                     NaN        1.0
KJ O'Brien                   NaN        1.0
AR McBrine                   NaN        0.0


Match : 20

Team 1 Score:

                    runs_off_bat  is_wicket
Najeeb Tarakai              90.0        NaN
Mohammad Nabi               34.0        NaN
Karim Janat                 20.0        NaN
Samiullah Shenwari          17.0        NaN
BJ McCarthy                  NaN        5.0
SR Thompson                  NaN        2.0
J Mulder                     NaN        1.0
GH Dockrell                  NaN        0.0

Team 2 Score:

                 runs_off_bat  is_wicket
PR Stirling              34.0        NaN
WTS Porterfield          22.0        NaN
L Tucker                  9.0        NaN
J Mulder                  5.0        NaN
Rashid Khan               NaN        5.0
Karim Janat               NaN        3.0
Shapoor Zadran            NaN        1.0
Amir Hamza                NaN        0.0


Match : 21

Team 1 Score:

                    runs_off_bat  is_wicket
Mohammad Nabi               89.0        NaN
Mohammad Shahzad            72.0        NaN
Usman Ghani                 23.0        NaN
Samiullah Shenwari          13.0        NaN
KJ O'Brien                   NaN        4.0
J Mulder                     NaN        2.0
BJ McCarthy                  NaN        1.0
AR McBrine                   NaN        1.0

Team 2 Score:

                 runs_off_bat  is_wicket
GC Wilson                59.0        NaN
PR Stirling              49.0        NaN
SR Thompson              43.0        NaN
WTS Porterfield          16.0        NaN
Rashid Khan               NaN        3.0
Amir Hamza                NaN        2.0
Karim Janat               NaN        2.0
Mohammad Nabi             NaN        2.0


Match : 22

Team 1 Score:

                runs_off_bat  is_wicket
E Lewis                100.0        NaN
J Charles               79.0        NaN
KA Pollard              22.0        NaN
AD Russell              22.0        NaN
JJ Bumrah                NaN        3.0
RA Jadeja                NaN        2.0
Mohammed Shami           NaN        1.0
B Kumar                  NaN        0.0

Team 2 Score:

               runs_off_bat  is_wicket
KL Rahul              110.0        NaN
RG Sharma              62.0        NaN
MS Dhoni               43.0        NaN
V Kohli                16.0        NaN
DJ Bravo                NaN        2.0
AD Russell              NaN        1.0
KA Pollard              NaN        1.0
CR Brathwaite           NaN        0.0


Match : 23

Team 1 Score:

                runs_off_bat  is_wicket
J Charles               43.0        NaN
LMP Simmons             19.0        NaN
CR Brathwaite           18.0        NaN
KA Pollard              13.0        NaN
A Mishra                 NaN        3.0
JJ Bumrah                NaN        2.0
R Ashwin                 NaN        2.0
Mohammed Shami           NaN        2.0

Team 2 Score:

            runs_off_bat  is_wicket
RG Sharma           10.0        NaN
AM Rahane            4.0        NaN
AD Russell           NaN        0.0
S Badree             NaN        0.0


Match : 24

Team 1 Score:

               runs_off_bat  is_wicket
EJ Villani             73.0        NaN
MM Lanning             60.0        NaN
AJ Blackwell            8.0        NaN
BL Mooney               1.0        NaN
LM Kasperek             NaN        1.0
HR Huddleston           NaN        1.0
LMM Tahuhu              NaN        1.0
SW Bates                NaN        1.0

Team 2 Score:

                  runs_off_bat  is_wicket
AE Satterthwaite          40.0        NaN
SW Bates                  26.0        NaN
LMM Tahuhu                10.0        NaN
RH Priest                  7.0        NaN
A Wellington               NaN        3.0
KM Beams                   NaN        2.0
JL Jonassen                NaN        1.0
M Strano                   NaN        1.0


Match : 25

Team 1 Score:

                  runs_off_bat  is_wicket
SW Bates                  30.0        NaN
RH Priest                 20.0        NaN
AE Satterthwaite          13.0        NaN
EC Perry                  12.0        NaN
M Strano                   NaN        5.0
A Wellington               NaN        2.0
A Gardner                  NaN        1.0
KM Beams                   NaN        1.0

Team 2 Score:

                  runs_off_bat  is_wicket
EJ Villani                19.0        NaN
AJ Blackwell              14.0        NaN
MM Lanning                 9.0        NaN
A Gardner                  5.0        NaN
AM Peterson                NaN        4.0
EM Bermingham              NaN        2.0
HR Huddleston              NaN        2.0
AE Satterthwaite           NaN        1.0


Match : 26

Team 1 Score:

                  runs_off_bat  is_wicket
SW Bates                  31.0        NaN
AE Satterthwaite          18.0        NaN
RH Priest                 17.0        NaN
AM Peterson               15.0        NaN
A Wellington               NaN        4.0
KM Beams                   NaN        2.0
M Strano                   NaN        2.0
A Gardner                  NaN        0.0

Team 2 Score:

               runs_off_bat  is_wicket
AJ Blackwell           30.0        NaN
AJ Healy               12.0        NaN
A Wellington            8.0        NaN
MM Lanning              5.0        NaN
LMM Tahuhu              NaN        3.0
AC Kerr                 NaN        2.0
AM Peterson             NaN        2.0
HR Huddleston           NaN        2.0


Match : 27

Team 1 Score:

                runs_off_bat  is_wicket
HML Madushani           17.0        NaN
I Ranaweera              8.0        NaN
PM Weerakkody            7.0        NaN
KDU Prabodhani           6.0        NaN
KM Beams                 NaN        3.0
JL Jonassen              NaN        3.0
EA Perry                 NaN        1.0