In [1]:
import numpy as np 
import pandas as pd 
import seaborn as sns 
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv('International_T20_Data.csv')
pd.set_option('display.max_columns' , None)
df.sample(5)

,innings,meta.data_version,meta.created,meta.revision,info.dates,info.gender,info.match_type,info.outcome.by.wickets,info.outcome.winner,info.overs,info.player_of_match,info.teams,info.toss.decision,info.toss.winner,info.umpires,info.venue,info.city,info.outcome.by.runs,info.match_type_number,info.neutral_venue,info.outcome.method,info.outcome.result,info.outcome.eliminator,info.supersubs.New Zealand,info.supersubs.South Africa,info.bowl_out,info.outcome.bowl_out
1228,"[{'1st innings': {'team': 'Australia', 'delive...",0.9,2015-08-28,2,"[datetime.date(2015, 8, 26)]",female,T20,7.0,England,20,['SJ Taylor'],"['England', 'Australia']",field,England,"['NGB Cook', 'MJ Saggers']",County Ground,Chelmsford,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
114,"[{'1st innings': {'team': 'New Zealand', 'deli...",0.9,2020-06-26,1,['2018-06-28'],female,T20,7.0,England,20,['A Shrubsole'],"['New Zealand', 'England']",bat,New Zealand,"['NL Bainton', 'AG Wharf']",County Ground,Bristol,NaN,439.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
839,"[{'1st innings': {'team': 'New Zealand', 'deli...",0.9,2012-07-16,2,"[datetime.date(2008, 12, 26)]",male,T20,NaN,NaN,20,['CH Gayle'],"['New Zealand', 'West Indies']",bat,New Zealand,"['BF Bowden', 'AL Hill']",Eden Park,Auckland,NaN,NaN,NaN,NaN,tie,West Indies,NaN,NaN,NaN,NaN
627,"[{'1st innings': {'team': 'Namibia', 'deliveri...",0.9,2019-10-26,1,['2019-10-25'],male,T20,NaN,Namibia,20,['MG Erasmus'],"['Kenya', 'Namibia']",bat,Namibia,"['LE Hannibal', 'AG Wharf']",Dubai International Cricket Stadium,Dubai,87.0,969.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
859,"[{'1st innings': {'team': 'India', 'deliveries...",0.9,2010-05-02,2,"[datetime.date(2010, 5, 2)]",male,T20,NaN,India,20,['SK Raina'],"['India', 'South Africa']",field,South Africa,"['Aleem Dar', 'SJA Taufel']","Beausejour Stadium, Gros Islet",St Lucia,14.0,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
df.shape

(1417, 27)

In [4]:
print(df.columns)

Index(['innings', 'meta.data_version', 'meta.created', 'meta.revision',
       'info.dates', 'info.gender', 'info.match_type',
       'info.outcome.by.wickets', 'info.outcome.winner', 'info.overs',
       'info.player_of_match', 'info.teams', 'info.toss.decision',
       'info.toss.winner', 'info.umpires', 'info.venue', 'info.city',
       'info.outcome.by.runs', 'info.match_type_number', 'info.neutral_venue',
       'info.outcome.method', 'info.outcome.result', 'info.outcome.eliminator',
       'info.supersubs.New Zealand', 'info.supersubs.South Africa',
       'info.bowl_out', 'info.outcome.bowl_out'],
      dtype='object')

In [5]:
#Rename all the column names to their appropriate names, for example meta.created should be renamed as created_date
df.rename(columns = {'meta.data_version' : 'data_version' , 'meta.created' : 'created' , 'meta.revision' : 'revision' , 
                     'info.dates' : 'dates' , 'info.gender' : 'gender' , 'info.match_type' : 'match_type' ,
                     'info.outcome.by.wickets' : 'outcome.by.wickets' , 'info.outcome.winner' : 'outcome.winner' , 'info.overs' : 'overs' ,
                      'info.player_of_match' : 'player_of_match' , 'info.teams' : 'teams' , 'info.toss.decision' : 'toss.decision' ,
                       'info.toss.winner' : 'toss.winner', 'info.umpires' : 'umpires', 'info.venue' : 'venue', 'info.city' : 'city',
                       'info.outcome.by.runs' : 'outcome.by.runs', 'info.match_type_number' : 'match_type_number', 'info.neutral_venue' : 'neutral_venue',
                       'info.outcome.method' : 'outcome.method', 'info.outcome.result' : 'outcome.result', 'info.outcome.eliminator' : 'outcome.eliminator',
                       'info.supersubs.New Zealand' : 'supersubs.New Zealand', 'info.supersubs.South Africa' : 'supersubs.South Africa',
                       'info.bowl_out' : 'bowl_out', 'info.outcome.bowl_out' : 'outcome.bowl_out'
                    } , inplace = True)

In [6]:
df.sample(5)

,innings,data_version,created,revision,dates,gender,match_type,outcome.by.wickets,outcome.winner,overs,player_of_match,teams,toss.decision,toss.winner,umpires,venue,city,outcome.by.runs,match_type_number,neutral_venue,outcome.method,outcome.result,outcome.eliminator,supersubs.New Zealand,supersubs.South Africa,bowl_out,outcome.bowl_out
1306,"[{'1st innings': {'team': 'Pakistan', 'deliver...",0.9,2015-10-03,3,"[datetime.date(2015, 9, 30)]",female,T20,NaN,Pakistan,20,['Bismah Maroof'],"['Pakistan', 'Bangladesh']",bat,Pakistan,"['Rashid Riaz', 'Riazuddin']",Southend Club Cricket Stadium,Karachi,29.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1364,"[{'1st innings': {'team': 'West Indies', 'deli...",0.9,2016-03-20,2,"[datetime.date(2016, 3, 20)]",female,T20,NaN,West Indies,20,['SR Taylor'],"['Bangladesh', 'West Indies']",bat,West Indies,"['AK Chaudhary', 'CK Nandan']","MA Chidambaram Stadium, Chepauk",Chennai,49.0,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
260,"[{'1st innings': {'team': 'West Indies', 'deli...",0.9,2020-06-27,1,['2018-10-06'],female,T20,3.0,South Africa,20,['L Lee'],"['West Indies', 'South Africa']",field,South Africa,"['JS Wilson', 'JM Williams']","Brian Lara Stadium, Tarouba",Trinidad,NaN,508.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
743,"[{'1st innings': {'team': 'Australia', 'delive...",0.9,2013-02-22,1,"[datetime.date(2005, 2, 17)]",male,T20,NaN,Australia,20,['RT Ponting'],"['New Zealand', 'Australia']",bat,Australia,"['BF Bowden', 'AL Hill']",Eden Park,Auckland,44.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
691,"[{'1st innings': {'team': 'Bangladesh', 'deliv...",0.9,2020-02-03,1,['2020-01-25'],male,T20,9.0,Pakistan,20,['Babar Azam'],"['Pakistan', 'Bangladesh']",bat,Bangladesh,"['Shozab Raza', 'Ahsan Raza']",Gaddafi Stadium,Lahore,NaN,1033.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:
#Find out the top three venues which hosted the greatest number of matches.
Top_3_Venues = df['venue'].value_counts().head(3).index
Top_3_Venues

Index(['Dubai International Cricket Stadium', 'Sheikh Zayed Stadium',
       'Shere Bangla National Stadium'],
      dtype='object', name='venue')

In [8]:
df['match_type'].value_counts()

match_type
T20    1417
Name: count, dtype: int64

In [9]:
#Find out the pair of cricket teams who played the most number of T20 matches against each other.
df['teams'].value_counts().head(1).index

Index(['['England', 'Pakistan']'], dtype='object', name='teams')

In [10]:
s1 = list(df['outcome.winner'].value_counts().index)

In [11]:
s1

['Australia',
 'England',
 'India',
 'Pakistan',
 'South Africa',
 'New Zealand',
 'West Indies',
 'Sri Lanka',
 'Afghanistan',
 'Bangladesh',
 'Ireland',
 'Netherlands',
 'Scotland',
 'United Arab Emirates',
 'Namibia',
 'Zimbabwe',
 'Nepal',
 'Papua New Guinea',
 'Thailand',
 'Hong Kong',
 'Malaysia',
 'Oman',
 'Germany',
 'Kenya',
 'Singapore',
 'Canada',
 'Jersey',
 'Uganda',
 'United States of America',
 'China',
 'Spain',
 'Vanuatu',
 'Bermuda',
 'Belgium',
 'Kuwait',
 'Guernsey',
 'Japan',
 'Rwanda',
 'Sierra Leone',
 'Nigeria',
 'Romania',
 'Maldives',
 'Botswana',
 'Qatar',
 'Tanzania',
 'Italy',
 'Denmark',
 'Indonesia',
 'Mozambique',
 'ICC World XI',
 'Malawi',
 'Philippines',
 'Samoa',
 'Portugal',
 'Bahrain',
 'Bulgaria']

In [12]:
l = []
for i in s1:
    l.append((df['teams'].str.contains(i).sum()).tolist())
l

[214,
 216,
 204,
 226,
 192,
 190,
 195,
 182,
 75,
 137,
 128,
 80,
 67,
 56,
 34,
 76,
 40,
 35,
 35,
 50,
 35,
 35,
 17,
 30,
 18,
 23,
 10,
 13,
 14,
 9,
 6,
 12,
 12,
 3,
 12,
 6,
 6,
 6,
 7,
 11,
 3,
 10,
 16,
 6,
 3,
 4,
 6,
 3,
 6,
 4,
 3,
 4,
 2,
 3,
 2,
 3]

In [13]:
l1 = (df['outcome.winner'].value_counts().values.tolist())
l1

[132,
 130,
 121,
 117,
 101,
 97,
 85,
 69,
 51,
 50,
 48,
 38,
 33,
 25,
 25,
 22,
 22,
 21,
 17,
 17,
 15,
 14,
 13,
 11,
 9,
 8,
 6,
 6,
 5,
 5,
 5,
 5,
 4,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1]

In [14]:
ans = []
for i in range(len(l1)):
    ans.append(np.round((l1[i]/l[i]) * 100 , 2).tolist())
len(ans)

56

In [15]:
win = pd.DataFrame({'Country' : s1 , 'Win Percentage' : ans})
win
win_Percenatge = (win.sort_values(by = 'Win Percentage' , ascending = False).head().iloc[: , 0].values)
win_Percenatge
win.sort_values(by = 'Win Percentage' , ascending = False).head()

        Country  Win Percentage
33      Belgium          100.00
30        Spain           83.33
22      Germany           76.47
14      Namibia           73.53
8   Afghanistan           68.00

In [18]:
import ast

def get_scorecard(match_index):

    match = df.iloc[match_index]
    innings_data = ast.literal_eval(match['innings'])

    scorecards = []

    for inn in innings_data:

        innings_name = list(inn.keys())[0]
        innings_info = inn[innings_name]

        deliveries = innings_info['deliveries']

        batsman_runs = {}
        bowler_wickets = {}

        for delivery in deliveries:

            ball = list(delivery.values())[0]

            batsman = ball['batsman']
            bowler = ball['bowler']
            runs = ball['runs']['batsman']

            batsman_runs[batsman] = batsman_runs.get(batsman,0) + runs

            if 'wicket' in ball:
                bowler_wickets[bowler] = bowler_wickets.get(bowler,0) + 1

        batsman_df = pd.DataFrame(
            batsman_runs.items(),
            columns=['Batsman','Runs']
        ).sort_values(by='Runs',ascending=False).head(4)

        bowler_df = pd.DataFrame(
            bowler_wickets.items(),
            columns=['Bowler','Wickets']
        ).sort_values(by='Wickets',ascending=False).head(4)

        scorecard = pd.concat([batsman_df, bowler_df], axis=1)

        scorecards.append(scorecard)

    return scorecards

In [19]:
score1, score2 = get_scorecard(0)

print("First Innings Scorecard")
print(score1)

print("\nSecond Innings Scorecard")
print(score2)

First Innings Scorecard
     Batsman  Runs          Bowler  Wickets
0   AJ Finch  43.0  PADLR Sandakan      1.0
1  M Klinger  38.0   DAS Gunaratne      1.0
2    TM Head  31.0   JRMVB Sanjaya      1.0
4  AJ Turner  18.0             NaN      NaN
3        NaN   NaN      SL Malinga      2.0

Second Innings Scorecard
           Batsman  Runs      Bowler  Wickets
3    DAS Gunaratne  52.0         NaN      NaN
2   EMDY Munaweera  44.0   AJ Turner      2.0
0      N Dickwella  30.0  PJ Cummins      1.0
4  TAM Siriwardana  15.0         NaN      NaN
1              NaN   NaN     A Zampa      2.0